<?php

namespace Database\Seeders;

use App\Models\CampusBloc;
use Illuminate\Database\Seeder;

class CampusBlocSeeder extends Seeder
{
    public function run(): void
    {
        $blocs = [
            ['bloc_key' => 'mafami', 'nom' => 'MAFAMI', 'signification' => "Mpianatra, mpiasa, mpandraharaha Avy amin'ny Faritanin'ny Antananarivo MIray", 'fondation' => 'vers 1978', 'fondateurs' => 'Mr Julien', 'slogan' => null, 'objectifs' => "Fanampiana ny mpianatra avy any Antananarivo mandrato fianarana aty Mahajanga\nFifanampianana amin'ny fitadiavana asa\nFifandraisana maharitra eo amin'ny samy mpianatra", 'activites' => "AG (Assemblée Générale)\nPot de contact\nRéception de bloc\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions)", 'danse' => null, 'mampiavaka' => null, 'images' => ['MAFAMI1.jpg', 'MAFAMI2.jpg', 'MAFAMI3.jpg', 'MAFAMI4.jpg']],
            ['bloc_key' => 'set', 'nom' => 'SET', 'signification' => 'Solidarité des Etudiants venant de Tsaratanana', 'fondation' => '14 juillet 2009', 'fondateurs' => 'Mr Nantenaina Ohatra, Mr Mano et Mr Bien Rangé', 'slogan' => 'Firaisankina Fahendrena Fampandrosoana', 'objectifs' => "Fanampiana ny mpianatra avy any Tsaratanana\nFifandraisana maharitra eo amin'ny samy mpianatra", 'activites' => "AG (Assemblée Générale)\nRéception de bloc/Novices (Miss et Mister)\nActivités sportives (Match inter-promotions)", 'danse' => 'Tsinjaka Sakalava', 'mampiavaka' => 'Volamena', 'images' => ['SET1.jpg', 'SET2.jpg']],
            ['bloc_key' => 'aeom', 'nom' => 'AEOM', 'signification' => 'Solidarité des Etudiants Originaire de Mampikony', 'fondation' => 'vers 1995', 'fondateurs' => "Les membres fondent l'association", 'slogan' => null, 'objectifs' => "Fanampiana ny mpianatra\nFifanampianana amin'ny fiainana sy ny fahasarotan'ny fiainana\nFifandraisana maharitra", 'activites' => "AG (Assemblée Générale)\nBonne année/Pacques\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, Match SEUM)", 'danse' => null, 'mampiavaka' => "famokarana Tongolo (Capital d'Oignons)", 'images' => ['AEOM1.jpg', 'AEPM2.jpg']],
            ['bloc_key' => 'ueffort', 'nom' => 'UEFFORT', 'signification' => "Union des Etudiants venant de l'Ex-prefecture de FORT-dauphin", 'fondation' => 'vers 2002', 'fondateurs' => 'Mr Tsitomotsy Arsène, Dr Hery, Ministre Pobert', 'slogan' => null, 'objectifs' => "Fanampiana ny mpianatra avy lavitra indrindra avy any Fort Dauphin\nFifanampianana amin'ny fitadiavana asa\nFifandraisana eo amin'ny samy mpianatra\nFanampianana ireo mpianatra zandry", 'activites' => "Pot de contact\nHavoria Atiké\nBonne année\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, SEUM)", 'danse' => 'Androy (Ganaiké), Taolagnaro (Mangaliba), Bar (Karitaky)', 'mampiavaka' => null, 'images' => ['UEEFORT1.jpg', 'UEEFORT2.jpg', 'UEEFORT4.jpg']],
            ['bloc_key' => 'sebaum', 'nom' => 'SEBAUM', 'signification' => 'Solidarité des Etudiants de Befandriana nord Associé à l\'Université de Mahajanga', 'fondation' => 'vers 1987', 'fondateurs' => 'Les membres', 'slogan' => null, 'objectifs' => "Mampitambatra ny faritra Befandriana avaratra\nFifanampianana amin'ny fiainana sy hanamora ny fiainana\nFifandraisana maharitra eo amin'ny samy mpianatra", 'activites' => "AG (Assemblée Générale)\nReception porte\nRéception de bloc\nReception SERS\nRéception des Novices (Miss et Mister, dance traditionnelle, moderne)\nActivités sportives (Match inter-promotions, SEUM)", 'danse' => 'Bawejy, Antosy, Malesa', 'mampiavaka' => null, 'images' => ['SEBAUM1.jpg']],
            ['bloc_key' => 'aevafi', 'nom' => 'AEVAFI', 'signification' => 'Association des Etudiants venant de la region de VAtovavy FItovinany', 'fondation' => 'vers 1999', 'fondateurs' => 'Mr IBRAHIM', 'slogan' => null, 'objectifs' => "Fifanampianana eo amin'ny fianarana sy ny fahasarotan'ny fiainana\nFiraisankina\nFifandraisana", 'activites' => 'AG (Assemblée Générale)\nReception de bloc(+sortie)\nRéception Grand Sud\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, SEUM, Basket et volley, Moraingy)', 'danse' => 'Batselaka, Sadebaka, Dombolo, Basesa', 'mampiavaka' => null, 'images' => ['AEVAFI1.jpg', 'AEVAFI2.jpg', 'AEVAFI3.jpg']],
            ['bloc_key' => 'aefum', 'nom' => 'AEFUM', 'signification' => "Association des Etudiants Fenarois de l'Université de Mahajanga", 'fondation' => 'vers 1983', 'fondateurs' => 'President de la Cadre Betsileo', 'slogan' => null, 'objectifs' => "Fanampiana ny mpianatra avy lavitra\nFifanampianana eo amin'ny fianarana\nFifandraisana sy fanamorana ny fiainana", 'activites' => 'AG (Assemblée Générale)\nRéception des Novices (Miss et Mister)\nActivités sportives foot et basket (Match inter-promotions, inter-associations)', 'danse' => 'Dihy Betsileo (KIDODO)', 'mampiavaka' => null, 'images' => ['AEFUM1.jpg', 'AEFUM2.jpg']],
            ['bloc_key' => 'fimpafato', 'nom' => 'FIMPAFATO', 'signification' => "FIkambanan'ny MPianatra Avy amin'ny FAritanin'ny TOliara", 'fondation' => 'vers 1986', 'fondateurs' => 'Mr Julien', 'slogan' => null, 'objectifs' => "Fanampiana ny mpianatra avy amin'ny faritra Atsimon'ny Nosy\nHamoaka olom-banona ho reharehan'ny faritra Atsimo\nFifandraisana maharitra", 'activites' => 'AG (Assemblée Générale)\nRepas social\nOuverture de cellule de prière\nRéception des Novices (Miss et Mister)\nActivités sportives foot et basket (Match inter-promotions)', 'danse' => 'TSAPIKY', 'mampiavaka' => null, 'images' => ['FIMPAFATO.jpg']],
            ['bloc_key' => 'seora', 'nom' => 'SEORA', 'signification' => "Solidarité des Etudiants Originaire d'Antsohihy", 'fondation' => 'vers 1987', 'fondateurs' => "les membres qui fondent d'associations", 'slogan' => null, 'objectifs' => "Fanampiana ny mpianatra amin'ny fianarana\nFitadiavana nahombiazana\nFifandraisana maharitra eo amin'ny samy mpianatra eto amin'ny université Mahajanga", 'activites' => 'AG (Assemblée Générale)\nBonne année/Sortie de pacques\nRéception de Dinosaure\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions 2fois pas ans)', 'danse' => 'Antosy, Bawejy, Malesa, Salesa, Alalaosy', 'mampiavaka' => 'Drakaka (Crabes)', 'images' => ['SEORA1.jpg', 'SEORA2.jpg']],
            ['bloc_key' => 'semen', 'nom' => 'SEMEN', 'signification' => 'Solidarité des Etudiants venant de la region de MENabe', 'fondation' => 'vers 2004', 'fondateurs' => 'Dr Rhejaly', 'slogan' => 'Filongoa-Faihira-Faheza', 'objectifs' => "Fanampiana ny mpianatra avy amin'ny faritra Menabe\nFifanampianana amin'ny fitadiavana asa\nFifandraisana maharitra", 'activites' => 'AG (Assemblée Générale)\nRéception des Novices (Miss et Mister)\nArrosage 2ème année (L2)\nActivités sportives (Match inter-promotions, SEUM)', 'danse' => 'KILALAKY, Tsinjaky DABA', 'mampiavaka' => 'Fambolena Tsaramaso', 'images' => ['SEMEN1.jpg', 'SEMEN2.jpg']],
            ['bloc_key' => 'fimtama', 'nom' => 'FIMTAMA', 'signification' => "FIkambanan'ny Mpianatra TAtsinanana eto MAhajanga", 'fondation' => '10 Mai 1980', 'fondateurs' => 'Dr Talata Michel', 'slogan' => 'Tatsinagnana uni Ensemble, nous pouvons réussir', 'objectifs' => "Fampivondronana ny mpianatra avy any Toamasina\nFifanampianana amin'ny fiainana\nFifandraisana maharitra eo amin'ny samy mpianatra", 'activites' => 'Pot de contact\nAG (Assemblée Générale)/Anniversaire\nBonne année, excursion\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, par porte)', 'danse' => 'BASESA, WATSAWATSA', 'mampiavaka' => 'Café, jirofo, Vanille', 'images' => ['FIMTAMA.jpg']],
            ['bloc_key' => 'uenam', 'nom' => 'UENAM', 'signification' => "Union des Etudiants Natifs d'Amoron'i Mania", 'fondation' => '11 Mai 2011, officialisé en 2012', 'fondateurs' => 'Dr Bernard', 'slogan' => null, 'objectifs' => "Fanampiana ny mpianatra ahatagny antanana\nFifanampianana amin'ny fitadiavana asa\nFifandraisana maharitra eo amin'ny samy mpianatra\nFanomezana lanja ny agnaran-dRay", 'activites' => 'AG (Assemblée Générale)\nPot de contact\nRéception des Novices (Miss et Mister)\nSortie de Promotion\nActivités sportives foot et basket (Match inter-promotions)', 'danse' => 'KIDODO', 'mampiavaka' => 'SAVIKA', 'images' => []],
            ['bloc_key' => 'aesa', 'nom' => 'AESA', 'signification' => "Association des Etudiants Solidaire d'Ambatoboeny", 'fondation' => 'vers 2008', 'fondateurs' => 'Mr Andry Rivo', 'slogan' => null, 'objectifs' => "Fanampiana ny mpianatra\nFifanampianana amin'ny fiainana andavanandro\nFifandraisana sy fampianarana ireo zandry", 'activites' => 'AG (Assemblée Générale)\nGrande soirée\nConcours Miss et Mister/Dance\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, par filière, SEUM, par association)', 'danse' => 'Tsinjaky Sakalava, Base 15', 'mampiavaka' => 'fambolena Lojy sy Voanjo', 'images' => ['AESA1.jpg', 'AESA2.jpg']],
            ['bloc_key' => 'ajeum', 'nom' => 'AJEUM', 'signification' => 'Association des Jeunes Universitaire venant de Marovoay', 'fondation' => 'vers 2011', 'fondateurs' => "les membres de l'association", 'slogan' => null, 'objectifs' => "Fanampiana eo amin'ny lafiny fianarana\nFanosehana ireo zandry mba ho tafita\nFiraisankinan'ny mpianatra avy any Marovoay", 'activites' => 'AG (Assemblée Générale)\nConcours de dance\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, SEUM)', 'danse' => 'Dihy Sakalava', 'mampiavaka' => 'Fambolem-bary (Capital du riz)', 'images' => ['AJEUM1.jpg', 'AJEUM2.jpg', 'AJEUM3.jpg', 'AJEUM4.jpg', 'AJEUM5.jpg']],
            ['bloc_key' => 'senum', 'nom' => 'SENUM', 'signification' => "Solidarité des Etudiants venant de Nosy-be à l'Université de Mahajanga", 'fondation' => 'vers 2005', 'fondateurs' => 'Dr Bachiro', 'slogan' => null, 'objectifs' => "Fifanampianana eo amin'ny samy mpianatra\nFanamorana ny fiainan'ny mpianatra\nFifandraisana maharitra", 'activites' => 'AG (Assemblée Générale)\nConcours Miss et Mister\nRéception de bloc\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, inter-associations)', 'danse' => 'SALEGY, TSOTSOBE, DIAMBOAY, MOGOJO', 'mampiavaka' => 'Ylang-Ylang, KATAKATA, Vanille', 'images' => ['SENUM1.jpg', 'SENUM2.jpg', 'SENUM3.jpg']],
            ['bloc_key' => 'triangle', 'nom' => 'TRIANGLE VERT', 'signification' => "Mpianatra, mpiasa, mpandraharaha Avy amin'ny Faritanin'ny Antananarivo MIray", 'fondation' => 'vers 1993', 'fondateurs' => 'Pr Jean Ralay', 'slogan' => "Vagnon'Aina, Vagnon-Karena", 'objectifs' => "Fampitambarana ny mpianatra zanaka SAVA\nFifanampianana amin'ny fiainana andavanandro\nFifandraisana maharitra", 'activites' => 'AG (Assemblée Générale)\nKAYAMBA\nRéception de bloc\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, inter-associations, par porte)', 'danse' => 'SALEGY', 'mampiavaka' => null, 'images' => ['TRIANGLE VERT1.jpg', 'TRIANGLE VERT2.jpg']],
            ['bloc_key' => 'uesdiana', 'nom' => 'UES-DIANA', 'signification' => 'Union des Etudiants Solidaire de DIANA', 'fondation' => 'vers 2015', 'fondateurs' => 'Mr RABEARINY Eduord Chrissant', 'slogan' => null, 'objectifs' => "Fanomezana lanja ny fianarana\nFifanampianana amin'ny fitadiavana asa\nFiraisankinan'ny mpianatra avy amin'ny faritra DIANA", 'activites' => 'AG (Assemblée Générale)\nRéception des Novices (Miss et Mister, dance traditionnelle)\nActivités sportives (Match inter-promotions, inter-association, SEUM)', 'danse' => 'TROTROBE', 'mampiavaka' => null, 'images' => ['UES-DIANA1.jpg', 'UES-DIANA2.jpg']],
            ['bloc_key' => 'mampiami', 'nom' => 'MAMPIAMI', 'signification' => "MAromangagn'e MPIanatry Antesaka MIraindraiky / MAromangagn'e MPIanatry Atsimo-antsinanana MIraindraiky", 'fondation' => '22 juillet 2006', 'fondateurs' => 'Mr Lahijosy Mirido Raelson', 'slogan' => null, 'objectifs' => "Rassembler et Unifier toute les etudiants venant de la region Sud Est\nRaffermir la solidarité entre les Diaspora", 'activites' => 'AG (Assemblée Générale)\nPot de contact\nCours de langue\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, Match Grand Sud)', 'danse' => null, 'mampiavaka' => 'Jirofo, Café, Letchi', 'images' => ['MAMPIAMI1.jpg', 'MAMPIAMI2.jpg', 'MAMPIAMI3.jpg']],
            ['bloc_key' => 'aina', 'nom' => 'AINA', 'signification' => "Association des Intellectuelles Natifs d'Andapa", 'fondation' => '14 Août 2014', 'fondateurs' => 'Mr Patrick Jannet', 'slogan' => "l'union fait la force", 'objectifs' => "Fanampiana ny mpianatra avy any Andapa\nFifanampianana eo amin'ny fiainana andavanandro\nFampifandraisana ny mpianatra sy ny firaisankina maharitra", 'activites' => 'AG (Assemblée Générale)\nConcours de dance, Karaoké\nRéception des Novices (Miss et Mister)\nActivités sportives foot et basketball (Match inter-promotions, SEUM, Inter-associations)', 'danse' => null, 'mampiavaka' => null, 'images' => ['AINA1.jpg', 'AINA2.jpg']],
            ['bloc_key' => 'uemar', 'nom' => 'UEMar', 'signification' => 'Union des Etudiants Marambitsy', 'fondation' => 'vers 2007', 'fondateurs' => "Les membres qui fondent l'association", 'slogan' => 'Filongoa Maiva', 'objectifs' => "Fifanampianana amin'ny fahasarotan'ny fiainana\nFampiraisana ny faritra mitsinjo sy soalala\nFiraisankinan'ny mpianatra", 'activites' => 'AG (Assemblée Générale)\nConcours Miss et Mister (membres)\nKaraoké\nMoraingy\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, SEUM, inter-filière, par Commune, par porte)', 'danse' => 'MINOTSIKY, PEKA-TRATRA, TROMBA-BIBY, TROMBA', 'mampiavaka' => 'Fambolena Katsaka sy Vary', 'images' => ['UEMar.jpg']],
            ['bloc_key' => 'sema', 'nom' => 'SEMA', 'signification' => 'Solidarité des Etudiants venant de MAevatanana', 'fondation' => 'vers 2011', 'fondateurs' => 'Mr Jules Man', 'slogan' => null, 'objectifs' => "Fampitambarana ny mpianatra avy any Maevatanana mandrato fianarana eto mahajanga\nFifanampianana amin'ny fitadiavana asa\nFiraisankina maharitra", 'activites' => 'AG (Assemblée Générale)\nPot de contact\nRéception de bloc\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, inter-associations)', 'danse' => 'Dance LAMACHINE', 'mampiavaka' => 'Volamena sy ny fambolena Black-eyes', 'images' => ['SEMA1.jpg', 'SEMA2.jpg']],
            ['bloc_key' => 'tampama', 'nom' => 'TAMPAMA', 'signification' => "Tamingan'Analalava Mandalim-PAhaizana eto MAhajanga", 'fondation' => 'vers 1986', 'fondateurs' => "Les membres qui l'ont fondée", 'slogan' => null, 'objectifs' => "Fampitambarana ny mpianatra avy any Maevatanana mandrato fianarana eto mahajanga\nFifanampianana amin'ny fitadiavana asa\nFiraisankina maharitra", 'activites' => 'AG (Assemblée Générale)\nRéception de Dinosaure\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, inter-associations)', 'danse' => 'Antosy, Bawejy, Malesa', 'mampiavaka' => null, 'images' => []],
            ['bloc_key' => 'aesva', 'nom' => 'AESVA', 'signification' => 'Association des Etudiants Solidaires de VAkinankaratra', 'fondation' => 'vers 2016', 'fondateurs' => 'Pr RANDRIAMBOLOLONA Théophile et Mr Solofo', 'slogan' => null, 'objectifs' => "Fampivondronana ny mpianatra avy any amin'ny faritra vakinankaratra\nFifanampianana amin'ny fiainana andavanandro\nFiraisankina maharitra sy fifanampiana eo amin'ny lafiny fianarana", 'activites' => 'AG (Assemblée Générale)\nPot de contact\nRéception des Novices (Miss et Mister)\nSortie\nActivités sportives (Match inter-promotions, inter-associations, SEUM)', 'danse' => 'Dihy soroka, Velatanana', 'mampiavaka' => 'Legumes', 'images' => ['AESVA1.jpg', 'AESVA2.jpg', 'AESVA3.jpg']],
            ['bloc_key' => 'seorm', 'nom' => 'SEORM', 'signification' => 'Solidarité des Etudiants Originaire de la Region Melaky', 'fondation' => 'vers 2009', 'fondateurs' => '… ???', 'slogan' => null, 'objectifs' => "Fanamorana ny fiainan'ny mpianatra\nFifanampianana eo amin'ny fianarana\nFiraisankina maharitra\nFanamaivanana ny vesatry ny fiainana", 'activites' => 'AG (Assemblée Générale)\nBonne année ensemble\nRéception des Novices (Miss et Mister)\nSortie ensemble\nActivités sportives (Match inter-promotions, inter-associations, Grand Sud, SEUM)', 'danse' => 'Tsinjaky Daba, Kilalaky, Degoly', 'mampiavaka' => 'Fambolena Côcô (voanio)', 'images' => ['SEOREM1.jpg', 'SEOREM2.jpg']],
            ['bloc_key' => 'mgama', 'nom' => 'MGAMA', 'signification' => "Mpianatra Gaonan'Alaotra MAngoro", 'fondation' => '05 novembre 1981', 'fondateurs' => 'Mr Rivo', 'slogan' => null, 'objectifs' => "Hampiray ny mpianatra avy any Antsihanaka\nFifanampianana eo amin'ny fiainana andavanandro\nFiraisankina maharitra", 'activites' => 'AG (Assemblée Générale)\nKaraoké\nConcours de dance\nConcours Miss et Mister\nRéception des Novices (Miss et Mister, dance traditionnelle)\nActivités sportives (Match inter-promotions, inter-associations, SEUM)', 'danse' => null, 'mampiavaka' => 'Fambolem-bary', 'images' => ['MGAMA.jpg']],
            ['bloc_key' => 'fimpama', 'nom' => 'FIMPAMA', 'signification' => "FIkambanan'ny MPianatra avy avaratra andrefan'Antsiranana eto MAhajanga", 'fondation' => 'vers 1977', 'fondateurs' => 'Membres', 'slogan' => null, 'objectifs' => "Firaisankina\nFahaiza-miaina\nFanampiana ireo mpianatra avy lavitra", 'activites' => 'AG (Assemblée Générale)\nConcours de dance (culture nord)\nConcours Miss et Mister\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, inter-associations, SEUM)', 'danse' => 'MIGODRO, TROMBA', 'mampiavaka' => 'Fambolena CACAO', 'images' => ['BLOCXXVI1.jpg', 'BLOCXXVI2.jpg', 'BLOCXXVI3.jpg']],
            ['bloc_key' => 'seob', 'nom' => 'SEOB', 'signification' => 'Solidarité des Etudiants Originaires de Bealanana', 'fondation' => 'vers 2000', 'fondateurs' => 'Zokibee miray', 'slogan' => 'Aza adigna ny raha nialagna antanagna, ny fianarana', 'objectifs' => "Fifanampianana eo amin'ny samy mpianatra\nFifanampianana amin'ny fitadiavana asa sy ny fiainana andavanandro\nFiraisankina maharitra", 'activites' => 'AG (Assemblée Générale)\nConcours Miss et Mister\nPot de porte\nRéception de bloc\nReception SERS\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, inter-associations)', 'danse' => 'Bawejy', 'mampiavaka' => 'DRAKIDRAKY fotsy maso', 'images' => ['SEOB.jpg']],
            ['bloc_key' => 'aep', 'nom' => 'AEP', 'signification' => 'Association des Etudiants de Port-bergé', 'fondation' => 'vers 2003', 'fondateurs' => 'Les membres', 'slogan' => null, 'objectifs' => "Fampitambarana ny mpianatra avy any Maevatanana mandrato fianarana eto mahajanga\nFifanampianana amin'ny fitadiavana asa\nFiraisankina maharitra", 'activites' => 'AG (Assemblée Générale)\nRéception de Dinosaure\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions, inter-associations, SEUM)', 'danse' => 'BAWEJY, MALESY, LALAOSY, ANTOSY', 'mampiavaka' => 'Black-Eyes', 'images' => ['AEP1.jpg', 'AEP2.jpg']],
            ['bloc_key' => 'fmaatm', 'nom' => 'FMAATM', 'signification' => "Fikambanan'ny Mpianatra Ambaratonga Ambony Terak'i Mandritsara", 'fondation' => '02 fevrier 1987', 'fondateurs' => 'Pr RAMAROSON sy Pr VITAMARINA', 'slogan' => null, 'objectifs' => "Fampitambarana ny mpianatra avy any Mandritsara\nFifanampianana amin'ny fiainana andavanandro\nFampirisihana ny mpianatra ho tafita lavitra\nFiraisankina maharitra eo amin'ny mpikambana", 'activites' => "AG (Assemblée Générale)\nDance culturelle par promotion\nConcours Miss et Mister\nRéception de porte (chaque porte l'organise)\nRéception de Dinosaure (+4ans=dinosaure)\nRéception des Novices (Miss et Mister)\nActivités sportives (Match inter-promotions (2fois par ans), inter-associations)", 'danse' => 'SESIBE (danse ensemble), MALESA', 'mampiavaka' => 'Voasary', 'images' => []],
            ['bloc_key' => 'semavi', 'nom' => 'SEMAVI', 'signification' => 'Solidarité des Etudiants MAhajanga VIlle', 'fondation' => '19 novembre 1996', 'fondateurs' => 'Pr Klain sy Pr William', 'slogan' => 'Fanabeazana-Fahendrena-Firaisankina', 'objectifs' => "Fampitambarana ny zanak'i Mahajanga\nFifanampianana amin'ny fianarana\nFiraisankina maharitra", 'activites' => 'AG (Assemblée Générale)\nRéception de bloc\nConcours Miss et Mister\nArtistique (fangalana artiste)\nRéception des Novices (Miss et Mister)\nSortie ensemble\nActivités sportives (Match inter-promotions, inter-associations, basket)', 'danse' => 'Dance Sakalava Boina', 'mampiavaka' => null, 'images' => []],
        ];

        foreach ($blocs as $index => $bloc) {
            $bloc['images'] = array_map(
                fn (string $file) => "images/campus/CAMPUS-UNIVERSITAIRE/{$file}",
                $bloc['images'],
            );

            CampusBloc::updateOrCreate(['bloc_key' => $bloc['bloc_key']], $bloc);
        }
    }
}
