<?php

namespace Database\Seeders;

use App\Models\Teacher;
use App\TeacherCategory;
use Illuminate\Database\Seeder;

class TeacherSeeder extends Seeder
{
    public function run(): void
    {
        $teachers = [
            [
                'name' => 'RAKOTOVELO Geoslin',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'rakotovelo.geoslin@isstm.mg',
                'photo_path' => 'images/teachers/rakotovelo-geoslin.jpg',
                'display_order' => 1,
            ],
            [
                'name' => 'AMBEONDAHY',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Mathématiques appliquées',
                'specialty_en' => 'Applied mathematics',
                'specialty_mg' => 'Matematika ampiharina',
                'email' => 'ambeondahy@isstm.mg',
                'display_order' => 2,
            ],
            [
                'name' => 'JOHANESA Fernand',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'BTP',
                'specialty_en' => 'Building and public works',
                'specialty_mg' => 'Fanorenana',
                'email' => 'johanesa.fernand@isstm.mg',
                'display_order' => 3,
            ],
            [
                'name' => 'MANASINA Ruffin',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Électricité',
                'specialty_en' => 'Electricity',
                'specialty_mg' => 'Herinaratra',
                'email' => 'manasina.ruffin@isstm.mg',
                'photo_path' => 'images/directeur.jpg',
                'display_order' => 4,
            ],
            [
                'name' => 'RAMAROJAONA Hubert',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Génie nucléaire et automatique',
                'specialty_en' => 'Nuclear and automatic engineering',
                'specialty_mg' => 'Injeniera nokleary sy mandeha ho azy',
                'email' => 'ramarojaona.hubert@isstm.mg',
                'photo_path' => 'images/teachers/ramarojaona-hubert.jpg',
                'display_order' => 5,
            ],
            [
                'name' => 'MAXWELL Djaffard',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'maxwell.djaffard@isstm.mg',
                'photo_path' => 'images/teachers/maxwell-djaffard.jpg',
                'display_order' => 6,
            ],
            [
                'name' => 'HARY Jean',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'hary.jean@isstm.mg',
                'photo_path' => 'images/teachers/hary-jean.jpg',
                'display_order' => 7,
            ],
            [
                'name' => 'RANDRIAMAITSO Télesphore',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Énergétique',
                'specialty_en' => 'Energy',
                'specialty_mg' => 'Angovo',
                'email' => 'randriamaitso.telesphore@isstm.mg',
                'photo_path' => 'images/teachers/randriamaitso-telesphore.jpg',
                'display_order' => 8,
            ],
            [
                'name' => 'TSANGANDRAZANA Annicet Judicael',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'tsangandrazana.annicet.judicael@isstm.mg',
                'photo_path' => 'images/teachers/tsangandrazana-annicet-judicael.jpg',
                'display_order' => 9,
            ],
            [
                'name' => 'ANDRIANIRINA Charles Bernard',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Électronique industrielle',
                'specialty_en' => 'Industrial electronics',
                'specialty_mg' => 'Elektronika indostrialy',
                'email' => 'andrianirina.charles.bernard@isstm.mg',
                'photo_path' => 'images/teachers/andrianirina-charles-bernard.jpg',
                'display_order' => 10,
            ],
            [
                'name' => 'ANDRIANANTENAINA Chrysostome',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Électronique et informatique',
                'specialty_en' => 'Electronics and computing',
                'specialty_mg' => 'Elektronika sy informatika',
                'email' => 'andrianantenaina.chrysostome@isstm.mg',
                'photo_path' => 'images/teachers/andrianantenaina-chrysostome.jpg',
                'display_order' => 11,
            ],
            [
                'name' => 'RAKOTOMALALA Lovasoa',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Physique et automatisme',
                'specialty_en' => 'Physics and automation',
                'specialty_mg' => 'Fizika sy fanaratana',
                'email' => 'ralovas@gmail.com',
                'photo_path' => 'images/teachers/rakotomalala-lovasoa.jpg',
                'display_order' => 12,
            ],
            [
                'name' => 'ANDRINIRINIAIMALAZA Fanambinantsoa Philibert',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Électronique et informatique industrielles',
                'specialty_en' => 'Industrial electronics and computing',
                'specialty_mg' => 'Elektronika indostrialy sy informatika',
                'email' => 'andriniriniaimalaza.fanambinantsoa.philibert@isstm.mg',
                'photo_path' => 'images/teachers/andriniriniaimalaza-philibert.jpg',
                'display_order' => 13,
            ],
            [
                'name' => 'FREDERIC Moise',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Génie logiciel',
                'specialty_en' => 'Software engineering',
                'specialty_mg' => 'Injeniera rindrambaiko',
                'email' => 'frederic.moise@isstm.mg',
                'photo_path' => 'images/teachers/frederic-moise.jpg',
                'display_order' => 14,
            ],
            [
                'name' => 'BEZARA Florent',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Informatique',
                'specialty_en' => 'Computer science',
                'specialty_mg' => 'Informatika',
                'email' => 'bezara.florent@isstm.mg',
                'photo_path' => 'images/teachers/bezara-florent.jpg',
                'display_order' => 15,
            ],
            [
                'name' => 'MELRAK Nykaise',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Biomédical',
                'specialty_en' => 'Biomedical',
                'specialty_mg' => 'Biomedikaly',
                'email' => 'melrak.nykaise@isstm.mg',
                'photo_path' => 'images/teachers/melrak-nykaise.jpg',
                'display_order' => 16,
            ],
            [
                'name' => 'RUINO Randriamihaja',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Physique et applications',
                'specialty_en' => 'Physics and applications',
                'specialty_mg' => 'Fizika sy fampiharana',
                'email' => 'ruino.randriamihaja@isstm.mg',
                'photo_path' => 'images/teachers/ruino-randriamihaja.jpg',
                'display_order' => 17,
            ],
            [
                'name' => 'RAVOHITRA Juvence',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Mécanique',
                'specialty_en' => 'Mechanics',
                'specialty_mg' => 'Mekanika',
                'email' => 'ravohitra.juvence@isstm.mg',
                'display_order' => 18,
            ],
            [
                'name' => 'RAJAONASY Iantara',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Génie Civil',
                'specialty_en' => 'Civil Engineering',
                'specialty_mg' => 'Injeniera sivily',
                'email' => 'rajaonasy.iantara@isstm.mg',
                'display_order' => 19,
            ],
            [
                'name' => 'RAZAFIARISON Ignace Abel J',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Energétique',
                'specialty_en' => 'Energy',
                'specialty_mg' => 'Angovo',
                'email' => 'razafiarison.ignace.abel.j@isstm.mg',
                'display_order' => 20,
            ],
            [
                'name' => 'RAKOTOMALALA Noelimihaja S',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Energétique et Génie Electrique',
                'specialty_en' => 'Energy and Electrical Engineering',
                'specialty_mg' => 'Angovo sy Injeniera Herinaratra',
                'email' => 'rakotomalala.noelimihaja.s@isstm.mg',
                'display_order' => 21,
            ],
            [
                'name' => 'RALINAVALONA Jhonson Jemi',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Anglaises/Education',
                'specialty_en' => 'English/Education',
                'specialty_mg' => 'Anglisy/Fanabeazana',
                'email' => 'ralinavalona.jhonson.jemi@isstm.mg',
                'display_order' => 22,
            ],
            [
                'name' => 'ABDULHAMID Asma',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Réseaux/Télécommunications',
                'specialty_en' => 'Networks/Telecommunications',
                'specialty_mg' => 'Tambajotra/Fifandraisan-davitra',
                'email' => 'abdulhamid.asma@isstm.mg',
                'display_order' => 23,
            ],
            [
                'name' => 'HANITRANIRINA Eloddy',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Conversion des énergies',
                'specialty_en' => 'Energy conversion',
                'specialty_mg' => "Ny fiovan'ny angovo",
                'email' => 'hanitranirina.eloddy@isstm.mg',
                'display_order' => 24,
            ],
            [
                'name' => 'HANTA Tina Olga',
                'category' => TeacherCategory::Permanent,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'hanta.tina.olga@isstm.mg',
                'display_order' => 25,
            ],
            [
                'name' => 'ANDRIANASOLONIRINA Ravoarimalala Naivosaona',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Agro-Management',
                'specialty_en' => 'Agro-Management',
                'specialty_mg' => 'Fitantanana ny fambolena',
                'email' => 'andrianasolonirina.ravoarimalala.naivosaona@isstm.mg',
                'display_order' => 26,
            ],
            [
                'name' => 'ANDRIANONY Mandimby Vonifandeferana',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Ingénierie des Systèmes Électriques Automatisés',
                'specialty_en' => 'Engineering of Automated Electrical Systems',
                'specialty_mg' => 'Injeniera momba ny Rafitra Elektrika Mandrindra Tena',
                'email' => 'andrianony.mandimby.vonifandeferana@isstm.mg',
                'display_order' => 27,
            ],
            [
                'name' => 'HABIB Nouraly',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Imagerie Médicale',
                'specialty_en' => 'Medical Imaging',
                'specialty_mg' => 'Sarin\'ny fitsaboana',
                'email' => 'habib.nouraly@isstm.mg',
                'display_order' => 28,
            ],
            [
                'name' => 'HERIPINOANARIMANANA Fenomora Evariste',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Aménagement et Génie urbain',
                'specialty_en' => 'Urban planning and engineering',
                'specialty_mg' => 'Fandrafetana tanàna sy injeniera',
                'email' => 'heripinoanarimanana.fenomora.evariste@isstm.mg',
                'display_order' => 29,
            ],
            [
                'name' => 'HOUSSEN Fils Auguste',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Énergie',
                'specialty_en' => 'Energy',
                'specialty_mg' => 'Angovo',
                'email' => 'houssen.fils.auguste@isstm.mg',
                'display_order' => 30,
            ],
            [
                'name' => 'JAONA Romain',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Bâtiment et Travaux publics',
                'specialty_en' => 'Building and Public Works',
                'specialty_mg' => 'Trano sy Asam-panjakana',
                'email' => 'jaona.romain@isstm.mg',
                'display_order' => 31,
            ],
            [
                'name' => 'JAONARANA Eric',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Ingénierie des matériaux et des matières premières',
                'specialty_en' => 'Materials and raw materials engineering',
                'specialty_mg' => 'Injeniera akora sy akora fototra',
                'email' => 'jaonarana.eric@isstm.mg',
                'display_order' => 32,
            ],
            [
                'name' => "LUCIEN FIDELE François d'Assise",
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Électronique Médicale',
                'specialty_en' => 'Medical Electronics',
                'specialty_mg' => 'Elektronika ara-pitsaboana',
                'email' => 'lucien.fidele.francois.d.assise@isstm.mg',
                'display_order' => 33,
            ],
            [
                'name' => 'MANANTSAINA Antoine Frédo',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'manantsaina.antoine.fredo@isstm.mg',
                'display_order' => 34,
            ],
            [
                'name' => 'MANIGNIAVY Sergio Andrew',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Génie Civil',
                'specialty_en' => 'Civil Engineering',
                'specialty_mg' => 'Injeniera sivily',
                'email' => 'manigniavy.sergio.andrew@isstm.mg',
                'display_order' => 35,
            ],
            [
                'name' => 'PETERA Benjamin',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Chimie des Substances Naturelles',
                'specialty_en' => 'Chemistry of Natural Substances',
                'specialty_mg' => 'Simia momba ny zavaboary voajanahary',
                'email' => 'petera.benjamin@isstm.mg',
                'display_order' => 36,
            ],
            [
                'name' => 'RABENIAINA Anjara Davio Ulrick',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Physique du Globe',
                'specialty_en' => 'Geophysics',
                'specialty_mg' => 'Fizikan\'ny tany',
                'email' => 'rabeniaina.anjara.davio.ulrick@isstm.mg',
                'display_order' => 37,
            ],
            [
                'name' => 'RAHARIVOLOLONA Ando Lalaina',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Bâtiment et Travaux publics',
                'specialty_en' => 'Building and Public Works',
                'specialty_mg' => 'Trano sy Asam-panjakana',
                'email' => 'raharivololona.ando.lalaina@isstm.mg',
                'display_order' => 38,
            ],
            [
                'name' => 'RAJAONASY Prosperia Riwoldek',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Droit',
                'specialty_en' => 'Law',
                'specialty_mg' => 'Lalàna',
                'email' => 'rajaonasy.prosperia.riwoldek@isstm.mg',
                'display_order' => 39,
            ],
            [
                'name' => 'RAKOTONDRAZAFY Florent',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Génie Mécanique',
                'specialty_en' => 'Mechanical Engineering',
                'specialty_mg' => 'Injeniera mekanika',
                'email' => 'rakotondrazafy.florent@isstm.mg',
                'display_order' => 40,
            ],
            [
                'name' => 'RALAINANDRASANA Heri-Zo',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Electromécanique et Informatique industriel',
                'specialty_en' => 'Electromechanics and Industrial IT',
                'specialty_mg' => 'Elektromekanika sy Informatika indostrialy',
                'email' => 'ralainandrasana.heri.zo@isstm.mg',
                'display_order' => 41,
            ],
            [
                'name' => 'RAMANAMPAMONJY Jean Claude',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Architecte',
                'specialty_en' => 'Architect',
                'specialty_mg' => 'Mpanao maritrano',
                'email' => 'ramanampamonjy.jean.claude@isstm.mg',
                'display_order' => 42,
            ],
            [
                'name' => 'RAMIANDRA Aina Clarc',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'ramiandra.aina.clarc@isstm.mg',
                'display_order' => 43,
            ],
            [
                'name' => 'RANAIVOSON Tahirisoa',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Hydrogéologie',
                'specialty_en' => 'Hydrogeology',
                'specialty_mg' => "Fikarohana rano ambanin'ny tany",
                'email' => 'ranaivoson.tahirisoa@isstm.mg',
                'display_order' => 44,
            ],
            [
                'name' => 'RANDRIAMANAFANA Alain',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Ingénierie des Systèmes Électriques Automatisés',
                'specialty_en' => 'Engineering of Automated Electrical Systems',
                'specialty_mg' => 'Injeniera momba ny Rafitra Elektrika Mandrindra Tena',
                'email' => 'randriamanafana.alain@isstm.mg',
                'display_order' => 45,
            ],
            [
                'name' => 'RANDRIANA Laurence Vanina',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Finance et Comptabilité',
                'specialty_en' => 'Finance and Accounting',
                'specialty_mg' => 'Fitantanam-bola sy kaonty',
                'email' => 'randriana.laurence.vanina@isstm.mg',
                'display_order' => 46,
            ],
            [
                'name' => 'RANDRIANANDRASANARIVO Raphaëlson Jacques',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'randrianandrasanarivo.raphaelson.jacques@isstm.mg',
                'display_order' => 47,
            ],
            [
                'name' => 'RANDRIANANTENAINA Todihasina Roselin',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Physique et applications',
                'specialty_en' => 'Physics and applications',
                'specialty_mg' => 'Fizika sy fampiharana',
                'email' => 'randrianantenaina.todihasina.roselin@isstm.mg',
                'display_order' => 48,
            ],
            [
                'name' => 'RANDRIANARISOA Ernest',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Ingénierie des Systèmes Électriques Automatisés',
                'specialty_en' => 'Engineering of Automated Electrical Systems',
                'specialty_mg' => 'Injeniera momba ny Rafitra Elektrika Mandrindra Tena',
                'email' => 'randrianarisoa.ernest@isstm.mg',
                'display_order' => 49,
            ],
            [
                'name' => 'RANDRIANARIVELO Eddy Flocaudel',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'randrianarivelo.eddy.flocaudel@isstm.mg',
                'display_order' => 50,
            ],
            [
                'name' => 'RAPATSALAHY Miary Andrianjaka',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Ingénierie logicielle',
                'specialty_en' => 'Software engineering',
                'specialty_mg' => 'Injeniera rindrambaiko',
                'email' => 'rapatsalahy.miary.andrianjaka@isstm.mg',
                'display_order' => 51,
            ],
            [
                'name' => 'RASOAHANITRINIAINA Théphile',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Économico-Gestion',
                'specialty_en' => 'Economics-Management',
                'specialty_mg' => 'Toekarena-Fitantanana',
                'email' => 'rasoahanitriniaina.thephile@isstm.mg',
                'display_order' => 52,
            ],
            [
                'name' => 'RASOANANDRASANA Marizia Roberta',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Physique',
                'specialty_en' => 'Physics',
                'specialty_mg' => 'Fizika',
                'email' => 'rasoanandrasana.marizia.roberta@isstm.mg',
                'display_order' => 53,
            ],
            [
                'name' => 'RASOLOHARISOA Marie Claudia',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Gestion',
                'specialty_en' => 'Management',
                'specialty_mg' => 'Fitantanana',
                'email' => 'rasoloharisoa.marie.claudia@isstm.mg',
                'display_order' => 54,
            ],
            [
                'name' => 'RAVELOMIARINA François',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => "Conversion d'Energie",
                'specialty_en' => 'Energy Conversion',
                'specialty_mg' => 'Fanovana angovo',
                'email' => 'ravelomiarina.francois@isstm.mg',
                'display_order' => 55,
            ],
            [
                'name' => 'RAZAFIMEVA Marie Odine',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Science de la Gestion',
                'specialty_en' => 'Management Science',
                'specialty_mg' => 'Siansa fitantanana',
                'email' => 'razafimeva.marie.odine@isstm.mg',
                'display_order' => 56,
            ],
            [
                'name' => 'RAZAFINDRABEHITA Lwanga Albert',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Mathématiques informatiques',
                'specialty_en' => 'Computer Mathematics',
                'specialty_mg' => 'Matematika informatika',
                'email' => 'razafindrabehita.lwanga.albert@isstm.mg',
                'display_order' => 57,
            ],
            [
                'name' => 'RHEVIHAJA Solo Njara',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => "Conversion d'Energie",
                'specialty_en' => 'Energy Conversion',
                'specialty_mg' => 'Fanovana angovo',
                'email' => 'rhevihaja.solo.njara@isstm.mg',
                'display_order' => 58,
            ],
            [
                'name' => 'ROGER Andriantsitoha Romuald',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Physique du Globe',
                'specialty_en' => 'Geophysics',
                'specialty_mg' => "Fizikan'ny tany",
                'email' => 'roger.andriantsitoha.romuald@isstm.mg',
                'display_order' => 59,
            ],
            [
                'name' => 'SOAFARA Erilà Franclin',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Mécanique Productique',
                'specialty_en' => 'Production Mechanics',
                'specialty_mg' => 'Mekanika famokarana',
                'email' => 'soafara.erila.franclin@isstm.mg',
                'display_order' => 60,
            ],
            [
                'name' => 'TOTOZAFINY Théodore',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Informatique et Electronique',
                'specialty_en' => 'Computers and Electronics',
                'specialty_mg' => 'Solosaina sy Elektronika',
                'email' => 'totozafiny.theodore@isstm.mg',
                'display_order' => 61,
            ],
            [
                'name' => 'VAVIZARA Sylvie',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Énergétique',
                'specialty_en' => 'Energy',
                'specialty_mg' => 'Angovo',
                'email' => 'vavizara.sylvie@isstm.mg',
                'display_order' => 62,
            ],
            [
                'name' => 'ZAFINTSALAMA Manohinaina Minontsoa Gabriel',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Électronique Médicale',
                'specialty_en' => 'Medical Electronics',
                'specialty_mg' => 'Elektronika ara-pitsaboana',
                'email' => 'zafintsalama.manohinaina.minontsoa.gabriel@isstm.mg',
                'display_order' => 63,
            ],
            [
                'name' => 'ZANAMASY Avatiana Augustin',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Bâtiment et Travaux publics',
                'specialty_en' => 'Building and Public Works',
                'specialty_mg' => 'Trano sy Asam-panjakana',
                'email' => 'zanamasy.avatiana.augustin@isstm.mg',
                'display_order' => 64,
            ],
            [
                'name' => 'RAPATSALAHY Miary',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Génie Logiciel',
                'specialty_en' => 'Software Engineering',
                'specialty_mg' => 'Injeniera rindrambaiko',
                'email' => 'rapatsalahy.miary@isstm.mg',
                'display_order' => 65,
            ],
            [
                'name' => 'RAZANAMANITRA Ranjasoanandrianina',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Gestion',
                'specialty_en' => 'Management',
                'specialty_mg' => 'Fitantanana',
                'email' => 'razanamanitra.ranjasoanandrianina@isstm.mg',
                'display_order' => 66,
            ],
            [
                'name' => 'RANDRIANALY Fetra',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Génie Électrique',
                'specialty_en' => 'Electrical Engineering',
                'specialty_mg' => 'Injeniera herinaratra',
                'email' => 'randrianaly.fetra@isstm.mg',
                'display_order' => 67,
            ],
            [
                'name' => 'RANDRIANASOLOMANGA N. R. Aurélie',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Langue',
                'specialty_en' => 'Language',
                'specialty_mg' => 'Fiteny',
                'email' => 'randrianasolomanga.n.r.aurelie@isstm.mg',
                'display_order' => 68,
            ],
            [
                'name' => 'RAKOTOMANGA Anjatiana',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Langue',
                'specialty_en' => 'Language',
                'specialty_mg' => 'Fiteny',
                'email' => 'rakotomanga.anjatiana@isstm.mg',
                'display_order' => 69,
            ],
            [
                'name' => 'TOTOZANDRY Jacquot',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Télécommunications et Réseaux',
                'specialty_en' => 'Telecommunications and Networks',
                'specialty_mg' => 'Fifandraisan-davitra sy Tambajotra',
                'email' => 'totozandry.jacquot@isstm.mg',
                'display_order' => 70,
            ],
            [
                'name' => 'RANDRIAMAHEFA Alido Soidry',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Génie Électrique',
                'specialty_en' => 'Electrical Engineering',
                'specialty_mg' => 'Injeniera herinaratra',
                'email' => 'randriamahefa.alido.soidry@isstm.mg',
                'display_order' => 71,
            ],
            [
                'name' => 'RANDRIA Amédé William',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Électronique et Informatique Industrielle',
                'specialty_en' => 'Electronics and Industrial Computing',
                'specialty_mg' => 'Elektronika sy Informatika Indostrialy',
                'email' => 'randria.amede.william@isstm.mg',
                'display_order' => 72,
            ],
            [
                'name' => 'RANDIMBISON Herizo',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Génie Civil',
                'specialty_en' => 'Civil Engineering',
                'specialty_mg' => 'Injeniera sivily',
                'email' => 'randimbison.herizo@isstm.mg',
                'display_order' => 73,
            ],
            [
                'name' => 'RAMAHALAZA Hardis',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Génie Électrique',
                'specialty_en' => 'Electrical Engineering',
                'specialty_mg' => 'Injeniera herinaratra',
                'email' => 'ramahalaza.hardis@isstm.mg',
                'display_order' => 74,
            ],
            [
                'name' => 'DONAZY Fanomezantsoa Trésor',
                'category' => TeacherCategory::Vacataire,
                'specialty_fr' => 'Génie Logiciel et Base de données',
                'specialty_en' => 'Software and Database Engineering',
                'specialty_mg' => 'Injeniera Rindrambaiko sy Angon-drakitra',
                'email' => 'donazy.fanomezantsoa.tresor@isstm.mg',
                'display_order' => 75,
            ],
        ];

        $descriptionTemplates = [
            TeacherCategory::Permanent->value => [
                'fr' => "Enseignant(e) permanent(e) spécialisé(e) en {specialty}, au service de la réussite des étudiants de l'ISSTM.",
                'en' => 'Permanent teacher specializing in {specialty}, serving the success of ISSTM students.',
                'mg' => "Mpampianatra maharitra manam-pahaizana manokana amin'ny {specialty}, manompo ny fahombiazan'ny mpianatra ISSTM.",
            ],
            TeacherCategory::Vacataire->value => [
                'fr' => "Enseignant(e) vacataire spécialisé(e) en {specialty}, au service de la réussite des étudiants de l'ISSTM.",
                'en' => 'Part-time teacher specializing in {specialty}, serving the success of ISSTM students.',
                'mg' => "Mpampianatra tapa-potoana manokana momba ny {specialty}, manompo ny fahombiazan'ny mpianatra ISSTM.",
            ],
        ];

        foreach ($teachers as $teacher) {
            $templates = $descriptionTemplates[$teacher['category']->value];
            $teacher['description_fr'] = str_replace('{specialty}', $teacher['specialty_fr'], $templates['fr']);
            $teacher['description_en'] = str_replace('{specialty}', $teacher['specialty_en'], $templates['en']);
            $teacher['description_mg'] = str_replace('{specialty}', $teacher['specialty_mg'], $templates['mg']);

            Teacher::updateOrCreate(['email' => $teacher['email']], $teacher);
        }
    }
}
